# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lets < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://let.sh/"
  version "0.2.46"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://install.let-sh.com/cli_0.2.46_darwin_arm64.tar.gz"
      sha256 "196b6e22c581108e0888ff89c86e5cfaa956e45ba03abff9ebdbd1a90aeae010"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.intel?
      url "http://install.let-sh.com/cli_0.2.46_darwin_amd64.tar.gz"
      sha256 "8b813450104d211d124e1ca608f8c7e8ea63801c6e722b523637c6a1408ba1d3"

      def install
        bin.install "program"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://install.let-sh.com/cli_0.2.46_linux_arm64.tar.gz"
      sha256 "7573acf2282fd1b9b1158f195f6fb4f7893f2ac4a877ecf46d17a9312c1aca56"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.intel?
      url "http://install.let-sh.com/cli_0.2.46_linux_amd64.tar.gz"
      sha256 "b9fe835d005270c86c3257e892d59f8f8882a93291ed0c84fa09d2f93f95b637"

      def install
        bin.install "program"
      end
    end
  end

  depends_on "git"
  depends_on "zsh" => :optional

  def caveats; <<~EOS
    Run `lets --help`
  EOS
  end

  test do
    system "#{bin}/program version"
  end
end
